server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Головне правило для React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Ігноруємо помилку відсутності favicon.ico
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
}