services:
  api:
    # Запускаємо сервер розробки
    command: npm run dev
    volumes:
      # Синхронізуємо код з папки backend у контейнер
      - ./backend:/app
      - /app/node_modules

  frontend:
    # Запускаємо Vite у режимі розробки
    command: npm run dev
    volumes:
      # Синхронізуємо код з папки frontend у контейнер
      - ./frontend:/app
      - /app/node_modules
    # Додаємо порт для Vite, якщо захочемо зайти напряму
    ports:
      - "5173:5173"